title: 'GithubPages y Jekyll'
description: 'JamStack, GithubPages - Antonio P√©rez Mart√≠n de Nicol√°s'
keywords: 'Implantaci√≥n de Aplicaciones Web'
url: 'https://abc.github.io' 

nav: 
  Inicio: '/'
  Tag: '/tags.html'
  L√≠nea de tiempo: '/timeline.html'
  About: '/about.html'
  Amigos: '/friendLink.html'
  Examenindex: '/examen/index.html'
  ExamenAlumnos: '/examen/alumnos.html'
  ExamenNotas: '/examen/notas.html'

author: true
name: 'Antonio P√©rez Mart√≠n De Nicol√°s'
NickName: 'Antonio'
webtitle: 'LEC'
bio: 'Estudiante de 2¬∫ de ASIR'
about: true
aboutyou: 'A por todas en el examen, se conf√≠aüôè.'
about: true
aboutyou: 'Jekyll con JamStack'
portraits: '/assets/lec.png' 

SNS: true
SNS-icon: 
  mail: ''
  weixin: '' 
  qq: ''
  github: 'https://github.com/antonioperezmartindenicolas'
  Codepen: ''
  weibo: ''
  instagram: ''
  Twitter: ''
  Dribbble: ''
  Facebook: ''
  Google: ''
  zhihu: ''
  juejin: ''
  twitch: ''

paginate: 2
paginatepath: ['page:num']

footer:
  since: 2023

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
pygmentsTheme: 'default'

friends:
  Antonio: 'https://github.com/antonioperezmartindenicolas'
  

disqus: false
disqus_url: '' 
livere: true
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' 
Gitment: false
Gitment_owner: ''  
Gitment_repo: ''  
client_id: ''  
client_secret: ''  

social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

baidu: true
baidu-url: ''
google: false
google-ID: ''

color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)